packages:
  - "apps/*"
  - "libs/*"

catalog:
  react: ^19.0.0
  react-dom: ^19.0.0
  "@types/react": ^19.0.1
  "@types/react-dom": ^19.0.1
  typescript: ^5.7.2
  typescript-eslint: ^8.13.0
  react-router: ^7.0.2
  "@react-router/node": ^7.0.2
  "@react-router/serve": ^7.0.2
